site_name: CategoricalTimeSeries.jl
nav:
    - Home: index.md
    - Correlations: correlations.md
    - Spectral properties: spectral_properties.md
    - Data clustering: data_clustering.md
    - Misc.: misc.md
theme: readthedocs
shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
