site_name: CategoricalTimeSeries.jl
nav:
    - Home: index.md
    - Correlations: correlations.md
    - Spectral properties: spectral_properties.md
    - Data clustering: data_clustering.md
    - Misc.: misc.md
theme: readthedocs
