site_name: CategoricalTimeSeries.jl

repo_url: https://github.com/johncwok/CategoricalTimeSeries.jl.git
edit_uri: ""

nav:
    - Home: index.md
    - Correlations: Correlations.md
    - Spectral properties: Spectral_properties.md
    - Data clustering: Data_clustering.md
    - Motif recognition: Motif_recognition.md
    - Miscellaneous: misc.md

theme: readthedocs

shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
