site_name: CategoricalTimeSeries.jl
nav:
    - Home: index.md
    - Correlations: Correlations.md
    - Spectral properties: Spectral_properties.md
    - Data clustering: Data_clustering.md
    - Miscellaneous: misc.md
theme: readthedocs
shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
