name = "CategoricalTimeSeries"
uuid = "f5116226-a574-5b1a-a4a4-91edc520f498"

authors = ["Corentin Nelias <cwokpoubelle@laposte.net>"]
version = "0.5"

[deps]
MotifRecognition = "2a4d4a8f-c57f-4bed-b307-c16a2225f1ea"
IntegerIB = "6503ae40-fab4-4b0f-9ca5-b3ead672bc37"
SpectralEnvelope = "ff710082-a9bc-57f3-81b5-980fc0acaaef"
SerialDependence = "807e6dab-69e6-5de1-b50c-dbd9513c50df"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0"
MotifRecognition = "^0.1"
